services:
  vector-db:
    image: qdrant/qdrant
    container_name: vector-db
    ports:
      - 6333:6333
    # environment:
    #   - VECTOR_DB_USER=admin
    #   - VECTOR_DB_PASSWORD=securepassword
    # volumes:
    #   - vector-db-data:/var/lib/vector-db
    # restart: unless-stopped